package constant

const (
	ENV_CONFIG_FILE_KEY  = "XWAY_BACKEND_CONFIG_FILE"
	ENV_SF_MACHINE_ID_KEY  = "XWAY_BACKEND_SF_MACHINE_ID"
	CONFIG_DEF_FILE = "config.yaml"
	CONFIG_FILE_TYPE = "yaml"

	// response
	RESPONSE_STATUS_OK = 0
	RESPONSE_STATUS_ERR = 1
)
